#!/bin/sh

set -e

BLUE=$(printf '\033[34m')
RESET=$(printf '\033[m')

logo() {
    echo "${BLUE}"
    cat << "EOF"
 __       __
/\ \     /\ \
\ \ \____\ \ \____     __
 \ \ '__`\\ \ '__`\  /'__`\
  \ \ \L\ \\ \ \L\ \/\ \L\ \
   \ \_,__/ \ \_,__/\ \___, \
    \/___/   \/___/  \/___/\ \
                          \ \_\
                           \/_/
        @nonballistic
EOF
echo "${RESET}"
}


build() {
    # build the cpp project
    ninja -C builddir/
}

run() {
    ./builddir/porkchop
}

plot(){
    python3 scripts/plot.py
}

if [ "$#" -ne 1 ]; then
    echo "not enough arguments"
    exit 1
fi

logo

if [ "$1" = "build" ]; then
    build
elif [ "$1" = "run" ]; then
    run
    plot
elif [ "$1" = "all" ]; then
    build
    echo "building the porkchop plot"
    run
    echo "plotting"
    plot
fi
